### ISSUE TITLE
MOUNT_UNMOUNT_FILESYSTEMS is only granted to system apps

### ISSUE THREAD

**Issue by walkmn** [DJI-Mobile-SDK-Tutorials/Android-ImportAndActivateSDKInAndroidStudio#17]
Following the official documentation https://developer.dji.com/mobile-sdk/documentation/android-tutorials/ImportAndActivateSDKInAndroidStudio.html developers should add a lot of permissions:
```
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
    <uses-permission android:name="android.permission.MOUNT_UNMOUNT_FILESYSTEMS" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
    <uses-feature android:name="android.hardware.camera" />
    <uses-feature android:name="android.hardware.camera.autofocus" />
```
Some of them `android.permission.MOUNT_UNMOUNT_FILESYSTEMS` has errors/security issue (from play market):
![image](https://user-images.githubusercontent.com/4289696/141995442-32fe0d70-233e-4f36-9f2c-33f7f027f0a1.png)
![image](https://user-images.githubusercontent.com/4289696/141995226-297715e9-c22d-4b08-bd8d-9692c348b35b.png)

This is maybe this is not issue, but question: Is dji sdk will be workable (or partically workable) if I remove the `android.permission.MOUNT_UNMOUNT_FILESYSTEMS` permission?

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/56435'>Zendesk ticket #56435</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by DJI-William** [comment]
This demo is too old, please refer to our final Sample's permission.
https://github.com/dji-sdk/Mobile-SDK-Android/blob/master/Sample%20Code/app/src/main/AndroidManifest.xml
