### ISSUE TITLE
ImportSDKDemo does not work

### ISSUE THREAD

**Issue by LorenzoCausa** [DJI-Mobile-SDK-Tutorials/Android-ImportAndActivateSDKInAndroidStudio#19]
I state that I am still trying to test it in the Android Studio emulator.
I load the code into the emulator, give all permissions and then the page closes with the message "registering, pls wait" and never gives the success message. (I have already entered the app key in the manifest)
Thanks in advance for any help.

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/61544'>Zendesk ticket #61544</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/61544'>Zendesk ticket #61544</a>:<br><br>Does your Android emulator support either of these two frameworks ('armeabi-v7a', 'arm64-v8a')? Actually, we don't recommend developers to use Android emulator to debug their software.
<br><p><em><small>°°°</small></em></p>

**Comment by LorenzoCausa** [comment]
I am still not able to use it in the emulator, but I tried to put it in my
mobile device and seems to work.
From now I will do my test directly on the phone.
Thanks!
