### ISSUE TITLE
Maybe missing steps to add layouts

### ISSUE THREAD

**Issue by xelmirage** [DJI-Mobile-SDK-Tutorials/Android-ImportAndActivateSDKInAndroidStudio#3]
In the readme.md there is no mention about editing layout files, that may be confusing.

**Comment by dji-dev** [comment]
Hi! Could you tell me what layout you want to implement in the tutorial sample code? Since this sample project just focus on import and activate DJI Android SDK in your Android Studio project, and use the "Basic" template of Android Studio, no customise layout. You can check our [FPVDemo](https://github.com/DJI-Mobile-SDK/Android-FPVDemo) tutorial for advanced SDK usage. Thanks!

**Comment by xelmirage** [comment]
Maybe I didn't explain clearly. As We know the ImportSDKDemo has some modification to the default project, such as add some widgets to activiti_main.xml, adding content_main.xml and menu_main.xml, and adding some strings and styles. These operation are not mentioned in the readme.md, so if users follows the steps in the readme.md, they might be confused. So my opinion is it's reasonable to mention all the modifications user needs to do to the default project.

**Comment by oliverou** [comment]
Hi, thanks for your advice. I have updated the "Creating an Android Studio Project" part by adding the "Create Basic Activity" detail in Readme file, please check it. The sample project is created from Android Studio's **Basic Activity** template, so all the UI like widgets are created automatically by Android Studio. You don't need to manually editing the layout files. Hope this help!

**Comment by xelmirage** [comment]
get it, thanks!

**Comment by oliverou** [comment]
You are welcome. I will close this issue then.
